CREATE TABLE produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    sku VARCHAR(50) NOT NULL UNIQUE,
    codigo_barras VARCHAR(13) NOT NULL UNIQUE,
    descricao TEXT,
    preco DECIMAL(10,2) NOT NULL,
    preco_custo DECIMAL(10,2),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    data_criacao TIMESTAMP NOT NULL,
    data_atualizacao TIMESTAMP,
    categoria_id BIGINT NOT NULL,
    CONSTRAINT chk_preco_positivo CHECK (preco > 0),
    CONSTRAINT chk_preco_custo_positivo CHECK (preco_custo IS NULL OR preco_custo > 0)
);
