CREATE TABLE estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantidade INT NOT NULL DEFAULT 0,
    estoque_minimo INT NOT NULL DEFAULT 0,
    data_criacao TIMESTAMP NOT NULL,
    data_atualizacao TIMESTAMP,
    produto_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_estoque_produto FOREIGN KEY (produto_id)
        REFERENCES produtos(id)
        ON DELETE CASCADE,
    CONSTRAINT chk_quantidade_nao_negativa CHECK (quantidade >= 0),
    CONSTRAINT chk_estoque_minimo_nao_negativo CHECK (estoque_minimo >= 0)
);


