CREATE TABLE estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantidade INT NOT NULL,
    observacao BOOLEAN NOT NULL,
    produto_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_estoque_produto FOREIGN KEY (produto_id)
        REFERENCES produtos(id)
        ON DELETE CASCADE,
    CONSTRAINT chk_quantidade_nao_negativa CHECK (quantidade >= 0)
);


