CREATE TABLE categoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE,
    data_criacao TIMESTAMP NOT NULL,
    data_atualizacao TIMESTAMP
);

-- Adicionar constraint FK na tabela produtos
ALTER TABLE produtos
ADD CONSTRAINT fk_produto_categoria FOREIGN KEY (categoria_id)
    REFERENCES categoria(id)
    ON DELETE RESTRICT;

