CREATE TABLE transacao_estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estoque_id BIGINT NOT NULL,
    quantidade INT NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    motivo VARCHAR(500),
    data_criacao TIMESTAMP NOT NULL,
    CONSTRAINT fk_transacao_estoque FOREIGN KEY (estoque_id)
        REFERENCES estoque(id)
        ON DELETE CASCADE,
    CONSTRAINT chk_tipo_transacao CHECK (tipo IN ('ENTRADA', 'SAIDA', 'AJUSTE'))
);

CREATE INDEX idx_transacao_estoque ON transacao_estoque(estoque_id);

CREATE INDEX idx_transacao_data ON transacao_estoque(data_criacao);

